---
AllCops:
  Exclude:
    - Rakefile
    - config.ru
    - db/schema.rb
    - bin/*
  TargetRubyVersion: 2.5.3
require:
  - rubocop-performance
  - rubocop-rspec
Documentation:
  Enabled: false
Layout/LineLength:
  Max: 120
Metrics/BlockLength:
  Exclude:
    - config/environments/*
    - config/application.rb
    - spec/**/*
Metrics/ClassLength:
  Exclude:
    - db/migrate/*.rb
  Max: 1500
Metrics/MethodLength:
  Exclude:
    - db/migrate/*.rb
  Max: 20
Style/AsciiComments:
  Enabled: false
Style/ClassAndModuleChildren:
  Exclude:
    - test/test_helper.rb
Style/CommentAnnotation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/GlobalVars:
  AllowedVariables:
    - $redis
Style/RedundantSort:
  Exclude:
    - app/models/degree.rb
Style/SymbolArray:
  Enabled: true
inherit_mode:
  merge:
    - Exclude
RSpec/DescribedClass:
  Enabled: false
