name: Analysis and Test

on: [push]

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby 2.5.3
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.5.3
      - name: Run RuboCop
        run: |
          gem install bundler
          bundle install --gemfile gemfiles/rubocop.gemfile --jobs 4 --retry 3
          bundle exec --gemfile gemfiles/rubocop.gemfile rubocop
  forspell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Hunspell
        run: |
          sudo apt-get install hunspell
      - name: Set up Ruby 2.5.3
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.5.3
      - name: Run Forspell
        run: |
          gem install forspell
          bundle exec forspell
  Rspec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          repository: say8425/PongDang-API-ENV
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Ruby 2.5.3
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.5.3
      - uses: zhulik/redis-action@v1.0.0
        with:
          redis version: 5
      - name: Run Rspec
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rspec
