name: Test and Analyze

on: [push]

jobs:
  rubocop:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Set up Ruby 2.5.x
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.5.x
      - name: Run RuboCop
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rubocop
  forspell:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Install Hunspell
        run: |
          sudo apt-get install hunspell
      - name: Set up Ruby 2.5.x
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.5.x
      - name: Run Forspell
        run: |
          gem install forspell --no-document
          forspell
  Rspec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Store ENV from AWS SecretManager
        uses: say8425/aws-secrets-manager-actions@v0.9.2
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_SECRET_MANAGER }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_SECRET_MANAGER }}
          AWS_DEFAULT_REGION: ap-northeast-2
          SECRET_NAME: pongdang-env-test
      - name: Set up Ruby 2.5.x
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.5.x
      - name: Use Redis Action
        uses: zhulik/redis-action@v1.0.0
        with:
          redis version: 5
      - name: Run Rspec
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rspec
