name: Test
on:
  push:
    branches-ignore:
      - master
jobs:
  cache_bundler:
    runs-on: ubuntu-latest
      env:
        RAILS_ENV: test
      steps:
        - name: Cache Bundler
          uses: actions/cache@v1
          with:
            path: vendor/bundle
            key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
            restore-keys: |
              ${{ runner.os }}-gem-
        - name: Bundle install
          run: |
            gem install bundler --no-document
            bundle config path vendor/bundle
            bundle install --jobs 4 --retry 3
  rubocop:
    runs-on: ubuntu-latest
    needs: cache_bundler
    env:
      RAILS_ENV: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Set up Ruby 2.5.x
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.5.x
      - name: Run RuboCop
        run: |
          gem install bundler --no-document
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          bundle exec rubocop
  forspell:
    runs-on: ubuntu-latest
    needs: cache_bundler
    env:
      RAILS_ENV: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Install Hunspell
        run: |
          sudo apt-get install hunspell
      - name: Set up Ruby 2.5.x
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.5.x
      - name: Run Forspell
        run: |
          gem install bundler --no-document
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          forspell
  brakeman:
    runs-on: ubuntu-latest
    needs: cache_bundler
    env:
      RAILS_ENV: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Set up Ruby 2.5.x
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.5.x
      - name: Run Brakeman
        run: |
          gem install bundler --no-document
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          bundle exec brakeman
  Rspec:
    runs-on: ubuntu-latest
    needs: cache_bundler
    env:
      RAILS_ENV: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Store ENV from AWS SecretManager
        uses: say8425/aws-secrets-manager-actions@v1
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_SECRET_MANAGER }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_SECRET_MANAGER }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          SECRET_NAME: pongdang-env-test
      - name: Set up Ruby 2.5.x
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.5.x
      - name: Use Redis Action
        uses: zhulik/redis-action@v1.0.0
        with:
          redis version: 5
      - name: Run Rspec
        run: |
          gem install bundler --no-document
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          bundle exec rspec
